### ISSUE TITLE
rootpath/dirpath problem

### ISSUE THREAD

**Issue by boneskull** [Morgul/trivialdb#22]
the `path` getter in `tdb.js` looks for `this.rootPath`, which is never set, throwing an exception from `path.join()`  it looks like `this._rootPath` *may* have been intended, but that doesn't get set before `this.path` gets accessed, so the exception is thrown anyway.  my next best guess is `this.options.rootPath` is what you want.  

I imagine some of this is to maintain backwards compatibility.  I'm going to send a PR to fix this

**Comment by boneskull** [comment]
OK, this looks fixed in `master`.  please publish!

**Comment by Morgul** [comment]
Currently, it is published under `1.4.0-beta.4`, which npm makes you install explicitly. I can publish as `1.4.0`, however (been meaning too). There are a couple edge cases with the new relations support that I wanted to get hammered out, but simply haven't had time.

I will get this published tonight. :)

**Comment by Morgul** [comment]
@boneskull Here's the npm docs on using pre-releases (it's a little wonky, tbh), if you need to use it before I get this published: https://docs.npmjs.com/misc/semver#prerelease-tags
