### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by Morgul** [Morgul/trivialdb#24]
I've started work on v2. The following is a list of the features I intend to have when it's released.

## Proposed features

* [X] Remove Models API
* [X] Convert to ES6 (~~dropping node < 4.X support~~ compile using babel)
* [x] Exclude example from npm package (space saving)
* [x] Include short UUID Generation (ex: `'HrILY'`, `'2JjA9s'`)
* [x] Add 'one per process' support (pull from `omega-logger`)
* [x] Add collection support
    * [x] Each namespace contains exactly one `TDB` instance per db name
    * [x] Each `.json` file is persisted inside a directory of the same name as the collection
* [x] Switch to Lodash Chaining (New API)
    * [x] `.get(key)` - dirty read; returns the value from the db (i.e., `return db.values[key]`)
    * [x] `.set(key, val)` - dirty write; does not trigger a `.sync()` (i.e., `db.values[key] = val`)
    * [x] `.del(key)` - dirty remove; does not trigger a `.sync()` (i.e., `delete db.values[key]`)
    * [x] `.load(key)` - safe read; returns a promise (i.e., `return Promise.resolve(db.values[key])`)
    * [x] `.save(key, val)` - safe write; returns a promise (i.e., `db.values[key] = val; return db.sync()`)
    * [x] `.remove(key)` - safe remove; returns a promise (i.e., `delete db.values[key]; return db.sync()`)
    * [x] `.reload()` - loads the JSON off disk
    * [x] `.sync()` - writes the JSON to disk
    * [x] `.query()` - starts a lodash chain function (i.e., `return _(_.values(db.values))`)
    * [x] `.filter(predicate)` - filter the db (i.e., `return db.query().filter(predicate)`)
    * [x] ~~`.map(predicate)` - map the db (i.e., `return db.query().map(predicate)`)~~ _use `query` instead_
    * [x] ~~`.reduce(predicate)` - reduce the db (i.e., `return db.query().reduce(predicate)`)~~ _use `query` instead_
* [x] Version-based syncing to disk
* [x] Keys with expirations
* [ ] Write new documentation
* [x] Write new example
* [x] Convert from [super-error](https://www.npmjs.com/package/super-error) to [make-error](https://www.npmjs.com/package/make-error)

**Comment by Morgul** [comment]
@boneskull, @whitelynx: FYI: I've released [v2.0.0-beta.1](https://github.com/Morgul/trivialdb/releases/tag/v2.0.0-beta.1), with all the specified features included.

No docs yet, I'll get them up in the next day or so, but the API's pretty easy to follow from this, or reading the code.

You will need to either edit your `package.json`, or `npm install trivialdb@v2.0.0-beta.1`. Give it a shot, and feel free to file issues.

**Comment by boneskull** [comment]
nice!  If I ever get back to the project I was using this for, I'll let you know how it goes.  :tired_face:

**Comment by Morgul** [comment]
Sweet! I'd love the feedback!
