### ISSUE TITLE
If using non-standard primary key name, JDBModel.filter() fails to populate primary key

### ISSUE THREAD

**Issue by whitelynx** [Morgul/trivialdb#25]
[In `JDBModel.filter()`](/Morgul/trivialdb/blob/v1.4.0/lib/models.js#L531), we set `model.$$values.id` to the retrieved ID, instead of setting `model.$$values[pk]` like we do [in `JDBModel.get()`](https://github.com/Morgul/trivialdb/blob/v1.4.0/lib/models.js#L487). This means we don't get the primary key populated, and instead get a superfluous `id` property added to `model.$$values`.

This could also cause more destructive issues if the model in question also has an `id` field that is not the primary key, though I don't think that's supported because of the `model.id` convenience property.

**Comment by Morgul** [comment]
@whitelynx This would make a good PR, if you felt like it. As I'm focused on v2 (and this code has been removed from that branch), this really would only be a maintenance thing. But, probably good to make happen, regardless.

**Comment by whitelynx** [comment]
Fixed by #26.
